<?php

return [
    'mbpos'         => [
        'harvestdev',
        'cultivatedev',
    ],
    'mbargprg'      => [
        'accuharvest',
        'argdetect',
        'fertilizer',
        'seeding',
        'nutrient',
        'pests',
    ],
    'mbser'         => [
        'promanage',
        'coopwork',
        'argdecision',
    ],
    'mbwarmhouse' => [
        'irrigation',
        'temperature',
        'weather',
        'envdetect',
        'video',
        'storage',
        'task',
        'alarm',
    ],
    'mbseeding' => [
        'seeding',
        'grafting',
        'gemination',
        'shiftoff',
    ],
    'mbpromanage' => [
        'expertsys',
        'pests',
        'promanage',
        'fertilizer',
        'devmanage',
    ],
    'mbquanmanage' => [
        'quanorigin',
        'devmanage',
        'quanmanage',
    ],
    'mbbusiness' => [
        'infocollect',
        'scancode',
        'packing',
        'diversity',
        'autoclean',
    ],
    'mbenvdetect' => [
        'autoctrl',
        'envdetect',
    ],
    'mbfeedctrl' => [
        'feedmanage',
        'oesmanage',
        'accufeed',
        'drinkmanage',
        'weighmanage',
        'elcidfy',
    ],
    'mbprocollect' => [
        'packing',
        'automilk',
        'autocollect',
    ],
    'mbdunghandler' => [
        'autoclean',
        'scrapboard',
        'changeboard',
        'wartersaving',
    ],
    'mbclean' => [
        'harmless',
        'fieldstorage',
        'treatpool',
        'methane',
        'fermentation',
    ],
    'mbondetect' => [
        'autodetect',
        'videodetect',
        'weatherdetect',
        'warterdetect',
    ],
    'mbgressmanage' => [
        'waterrobot',
        'watercycle',
        'geoimprove',
        'feedpush',
        'aerator',
        'optmanage',
        'labmanage',
    ],
    'mbcommanage' => [
        'quanorigin',
        'fishhealth',
        'waterenv',
        'sickdetect',
        'drugdetect',
        'waterquan',
    ],
    'mbpubser' => [
        'fishgrew',
        'deseasedetect',
        'pubsrc',
    ],
];
